// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kmhznueupelrpgfnxbyy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImttaHpudWV1cGVscnBnZm54Ynl5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NjU3OTAsImV4cCI6MjA2NTU0MTc5MH0.ph0YA5KLfcHREatTGPgaAHEJzUVRJjOx0Nxzf-1RpZI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);